apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxora-redis
  namespace: fluxora
  labels:
    app: fluxora-redis
    component: cache
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluxora-redis
  template:
    metadata:
      labels:
        app: fluxora-redis
        component: cache
        tier: data
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fluxora-redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - "--save"
            - "60"
            - "1"
            - "--loglevel"
            - "warning"
            - "--maxmemory"
            - "400mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: fluxora-redis-data
              mountPath: /data
            - name: tmp-dir
              mountPath: /tmp
      volumes:
        - name: fluxora-redis-data
          persistentVolumeClaim:
            claimName: fluxora-redis-pvc
        - name: tmp-dir
          emptyDir:
            sizeLimit: 50Mi
